# Fichier de financement pour le projet MLX for All
# Voir : https://docs.github.com/en/repositories/managing-your-repositorys-features-and-settings/managing-repository-settings/displaying-a-sponsor-button-in-your-repository

github: MrFlappy0
# patreon: # (optionnel)
# open_collective: # (optionnel)
# ko_fi: # (optionnel)
# tidelift: # (optionnel)
# community_bridge: # (optionnel)
# liberapay: # (optionnel)
# issuehunt: # (optionnel)
# otechie: # (optionnel)
# custom: # (optionnel)
